### ISSUE TITLE
License for original NOMP is GPL2 not MIT

### ISSUE THREAD

**Issue by webworker01** [s-nomp/s-nomp#74] opened 2018-10-01 19:31 UTC
z-nomp seems to have messed this up thinking they can change that license

**Comment by nimbosa** [comment] 2018-10-08 00:59
Yes, I can confirm that this is correct: https://github.com/zone117x/node-open-mining-portal/blob/master/LICENSE; it cannot be changed EXCEPT by the original author of NOMP but the change even then would not be retroactive. Code licensed under GPL2 would remain under GPL2. We will revert the commit that changed this in our repo.

Also, we are taking in changes from Z-nomp forks to reverse the trend towards fragmentation of Z-nomp implementations. We also welcome maintainers of the [official Zclassic repo](https://github.com/z-classic/z-nomp). Thanks!

**Comment by nimbosa** [comment] 2018-10-08 01:01
I further propose we craft a new Z-nomp incorporating s-nomp improvements. Thank you.

**Comment by egyptianbman** [comment] 2018-10-08 01:09
Hey @nimbosa, s-nomp was started by a group of pool maintainers that saw the fragmentation that you're referring to, where each coin began forking the pool software and modified it to their chain's needs. While the help from the chains was greatly appreciated, this introduced a lot of confusion as the changes each chain was making weren't compatible with each other.

Because of this, I don't think going back to Zclassic maintaining s-nomp is a good idea. Zclassic has gone from one maintainer to another with long periods of inactivity in between. These lapses of activity caused updates to stall. I believe that since pool maintainers use this code daily, it should be up to them to maintain it. We always welcome and appreciate help from coin maintainers but it doesn't quite make sense for any chain to carry the burden of having to maintain pool software.

If you'd like to discuss this further, please hop on discord for a chat. https://discord.gg/4mVaTsH

**Comment by nimbosa** [comment] 2018-10-09 18:34
Good points @egyptianbman! Heads up, we have [reverted](https://github.com/z-classic/z-nomp/commit/eb1e0dd61118bb751f5f17190928c3407b1b5f7b) this unilateral downstream license change. And all Z-nomp derivatives should probably be likewise alerted/reminded of the proper GPL2 license.

The invitation was made for closer coordination moving forward and should not affect your great work at s-nomp. What we should all achieve is avoid duplication of efforts and make improvements that are compatible with one another. BTW, [NOMP itself is up for grabs](https://github.com/zone117x/node-open-mining-portal/commit/aa44f3d4108673f2d2e26a5d5dd120af0e13810e) for exactly the same reasons you mentioned here, lack of consistently committed, full time maintainers, so the collective effort really makes sense.

Maybe a long-term vision would ideally (1) initially tie the lose ends of Z-nomp along with all Equihash implementations of NOMP; and (2) take on NOMP itself which also needs new maintainers to get along.

Cheers and keep up the good work! See you later on Discord. ;)

**Comment by nimbosa** [comment] 2018-10-09 18:38
The corresponding issue on Z-nomp has been closed: https://github.com/z-classic/z-nomp/issues/371. Thanks @webworker01!

**Comment by webworker01** [comment] 2018-10-11 14:07
Thanks, s-nomp is still not correctly licensed

**Closed as completed** 2019-07-21 21:59 UTC
